name: task_management_app
description: Cross-platform responsive Task Board built with Flutter, Riverpod, and local JSON persistence.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: '>=3.3.2 <3.4.0'
  shared_preferences: ^2.5.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
